kind: pipeline
name: copo_bo_api

clone:
  disable: true

steps:
  - name: docker
    image: appleboy/drone-ssh
    settings:
      host:
        - 172.28.222.65
        - 172.28.164.3
      username:
        from_secret: user
      password:
        from_secret: pwd
      port:
        from_secret: port
      script:
        - cd /root/copo_v2
        - git checkout -- .
        - git checkout master
        - git pull origin master
        #- git checkout -- .
        - go mod tidy
        - docker-compose down
        - docker rmi -f $(docker images --filter="reference=boadmin_service" --quiet)
        - docker rmi -f $(docker images -qf "dangling=true")
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bin/boadmin boadmin/boadmin.go
        - docker build -t boadmin_service -f boadmin/Dockerfile .
        - docker-compose up -d
    when:
      branch:
        - master
      event:
        - push
  
trigger:
  branch:
    - master
  event:
    - push
